builds:
  - id: vpa-analysis
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags:
      - "-X main.VERSION=$(VERSION) -s -w"
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
